version: "2.4"

services:

  # main service
  talebook:
    restart: always
    image: talebook/talebook
    volumes:
      - D:/testProgram/talebook_volume/data:/data
      - D:/testProgram/talebook/webserver:/var/www/talebook/webserver
      # favicon.ico，logo图等目录
      - D:/testProgram/talebook_volume/web:/var/www/talebook/app/dist
      # vue build编译代码
      - D:/testProgram/talebook_volume/app:/var/www/talebook/app
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    depends_on:
      - douban-rs-api

  # optional, for meta plugins
  # please set "http://douban-rs-api" in settings
  douban-rs-api:
    restart: always
    image: ghcr.io/cxfksword/douban-api-rs
